### ISSUE TITLE
Cost/licence dashboard

### ISSUE THREAD

**Issue by apenney-beeswax** [aerospike/aerospike-monitoring#29]
Hi,

We were wondering if it's possible for someone on the Aerospike side to take a look at adding a "cost dashboard" that would make it easier for us to track our usage vs our contract.

At the very least it would be nice to easily track # of clusters and storage (measured in the same way as the contract, not just disk used), along with total's across all running clusters!

We were about to build it, but we're not sure the right metrics exist and it would be better if this was done once and available to all customers!

**Comment by arrowplum** [comment]
Hi @apenney-beeswax We have a tool to do this in progress. (cc @rbotzer )
